### ISSUE TITLE
Need better concurrency control

### ISSUE THREAD

**Issue by duchatran** [SumoLogic/sumologic-netskope#5]
Currently code is using thread pool, but there can be multiple processes via cron jobs. Need to use process synchronization instead.

**Comment by duchatran** [comment]
Netskope has updated the API to return a 429 response when limit is hit. They also restrict to 4 requests per second.

**Comment by himanshu219** [comment]
Fix in https://github.com/SumoLogic/sumologic-netskope/pull/8
